Add 'Aantekening PB' filter
Amsterdam/GOB-Prepare pull request #321
Opened 2021-10-11 15:34 UTC by roel-devries

Lots of formatting/whitespace changes

2021-10-11 15:46 UTC, roel-devries commented on src/data/sql/brk/select.stukdeel.sql
> +            JOIN brk_prep.aantekening_kadastraal_object akt -- Only include AKT's
inner join -> filters aantekening PB

2021-10-12 08:30 UTC, RoelWKramer commented on src/data/brk.prepare.json
> +      "source": "https://developer.kadaster.nl/schemas/waardelijsten/AardAantekening/AardAantekening.csv",
This changes the datasource to kadaster's developer environment. Is this intentional?

2021-10-12 09:00 UTC, RoelWKramer requested changes
1 question

2021-10-12 10:40 UTC, RoelWKramer submitted a review, later dismissed

2021-10-12 14:40 UTC, RoelWKramer approved these changes

2021-10-12 14:41 UTC, merged